<?php
/**
 * @see Todopago_Modulodepago2_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<?php
$token = "token 21600a0757d4b32418c54e3833dd9d47f78186b4";
 
$curl = curl_init();
curl_setopt_array($curl, array(
	CURLOPT_HTTPHEADER => array(
		'Content-Type: application/json',
		 'Authorization:'.$token
	),
	CURLOPT_SSL_VERIFYPEER => true,
	CURLOPT_SSL_VERIFYHOST => 2,
	CURLOPT_RETURNTRANSFER => 1,
	CURLOPT_URL => 'https://api.github.com/repos/TodoPago/Plugin-Magento/releases/latest',
	CURLOPT_USERAGENT => 'Codular Sample cURL Request',
));

$resp = curl_exec($curl);
$http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
curl_close($curl);

$json_r = json_decode($resp, true);
$repo_version = substr($json_r['tag_name'], 1);

$tp_version = Mage::getConfig()->getModuleConfig("Todopago_Modulodepago2")->version;

if($http_status == 200){
	if(version_compare($repo_version, $tp_version, '>')){
?>
	<div style="font-weight: bold; margin: -10px 0 10px 0;">
		<div class="messageStackCaution larger message-notification">Todopago: Existe una version mas reciente del Plugin, puede revisarla desde <a href="https://github.com/TodoPago/Plugin-Magento">Github</a>.</div>
	</div>
<?php		
	}
}
?>




